project:
  type: website
  output-dir: docs
  render:
    - simplex.qmd

website:
  title: "Numerical Optimal Transport"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - simplex.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
